# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
      uses: pip install codecov-cli  
            codecovcli create-commit -t {$CODECOV_TOKEN}
            codecovcli create-report -t {$CODECOV_TOKEN}
            codecovcli do-upload -t {$CODECOV_TOKEN}
      with:
        flags: ${{ matrix.node-version }}
        fail_ci_if_error: true
        name: ${{ matrix.node-version }}
        verbose: true
